# Generated by Django 3.2.10 on 2024-06-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_electric',
            field=models.BooleanField(default=False),
        ),
    ]
