# Generated by Django 3.2.10 on 2024-06-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_brand_is_electric'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vehicle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.maincategory'),
        ),
    ]
