# Generated by Django 3.2.10 on 2024-07-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240701_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='version_fuel_type',
            field=models.CharField(default='Diesal', max_length=100),
        ),
    ]
