# Generated by Django 3.2.10 on 2024-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_vehicle_version_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryproducts',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='accessoryproducts',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
