# Generated by Django 3.2.10 on 2024-07-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240701_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryproducts',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
