# Generated by Django 3.2.10 on 2024-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_accessoryproducts_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryproducts',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
