# Generated by Django 3.2.10 on 2024-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_accessoryproducts_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryproducts',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
