# Generated by Django 3.2.10 on 2024-07-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_accessoryproducts_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoryproducts',
            name='discount_percentage',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='accessoryproducts',
            name='offer_price',
            field=models.FloatField(editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='accessoryproducts',
            name='price',
            field=models.FloatField(max_length=5),
        ),
    ]
