# Generated by Django 3.2.10 on 2024-07-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240702_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accessoryproducts',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='accessoryproducts',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accessoryproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
