# Generated by Django 3.2.10 on 2024-07-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20240705_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
