# Generated by Django 3.2.10 on 2024-07-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_product_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_category',
        ),
    ]
