# Generated by Django 3.2.10 on 2024-07-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_product_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='version_fuel_type',
        ),
    ]
