# Generated by Django 3.2.10 on 2024-07-08 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_subvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subvehicle_bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('electric', models.BooleanField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_vehicles_bike', to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SubVehicle_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('name', models.CharField(max_length=100)),
                ('version_fuel_type', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('electric', models.BooleanField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_vehicles_car', to='api.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='SubVehicle',
        ),
    ]
