# Generated by Django 3.2.10 on 2024-09-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20240809_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
    ]
